apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: achillessdk/argocd-fullcycle
  newTag: ea2123810585b3485a2674ab3a44dc31f232d932
